server:
  port:
    8888
spring:
  cloud:
    config:
      server:
        native:
          searchLocations: file:config-server/config-repo
  profiles:
    active: native
  application:
    name: config-server